version: "3.1"
services:
  app:
    image: performance-module
    build: 
      context: ./
    container_name: performance-module-app
    depends_on:
    - performance-db
    environment:
    - SPRING_DATASOURCE_URL=jdbc:postgresql://performance-db:5432/Performance1
    - SPRING_DATASOURCE_USERNAME=postgres
    - SPRING_DATASOURCE_PASSWORD=olivar
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
    - 8080:8090
    networks:
    - spring
    - postgres



  performance-db:
    container_name: performance-db
    image: postgres:11
    environment:
      POSTGRES_DB: Performance1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: olivar
      PGDATA: /data/postgres
    volumes:
    - postgres:/data/postgres
    expose: 
      - 5432
    ports: 
      - 5433:5432
    networks:
    - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
    - pgadmin:/var/lib/pgadmin
    ports:
    - 5050:80
    networks:
    - postgres
    restart: unless-stopped
      

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
      
volumes:
  postgres: null
  pgadmin: null